<?php

/**
 * @file
 * Stud Sol List Example.
 */

/**
 * @defgroup stud_sol_list Example: Stud Sol List
 * @ingroup examples
 * @{
 * Output nodes in the table with pagination.
 *
 * @see \Drupal\Core\Database\Query\PagerSelectExtender
 */

/**
 * Implements hook_theme().
 */
function stud_sol_list_theme() {
  // We use a template file to allow for translation of blocks of content.
  // Therefore we need to add this content at the theming layer.
  return [
    'stud_sol_list_description' => [
      'template' => 'description',
      'variables' => [],
    ],
  ];
}

/**
 * @} End of "defgroup stud_sol_list".
 */
